version: '3.7'

volumes:
    logs:
        driver: local

services:
    slim:
        image: php:7-alpine
        working_dir: /var/www
        command: sh -c "docker-php-ext-install pdo pdo_mysql && php -S 0.0.0.0:80 -t public"
        environment:
            docker: "true"
        ports:
            - 80:80
        volumes:
            - .:/var/www
            - logs:/var/www/logs
        network_mode: host
    mysql:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: slim-db
        volumes:
            - ./database:/docker-entrypoint-initdb.d
        network_mode: host